name: lappy
description: A cross-platform LLM client for Windows, macOS, and Linux.

publish_to: 'none'

version: 0.1.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  tray_manager: ^0.3.2
  macos_ui: ^2.1.9
  window_manager: ^0.4.3
  flutter_overlay_window: ^0.4.5
  file_picker: ^9.0.2
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
